// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqLLFQi0Q1H7Y1L7cKBPZG0nCM7mXCbo',
    appId: '1:910592114279:web:da61f87059074ade235ec2',
    messagingSenderId: '910592114279',
    projectId: 'cost-deko',
    authDomain: 'cost-deko.firebaseapp.com',
    storageBucket: 'cost-deko.appspot.com',
    measurementId: 'G-CZVRFFZLRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlUxAVLs8skjp9YM8jOU2Oze4qHhXcvo',
    appId: '1:910592114279:android:1e245dc415000c77235ec2',
    messagingSenderId: '910592114279',
    projectId: 'cost-deko',
    storageBucket: 'cost-deko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ty9mkwlhTNU2VWS3AmWDyr5wT5a_CKM',
    appId: '1:910592114279:ios:1a1c6b9558ecc5ca235ec2',
    messagingSenderId: '910592114279',
    projectId: 'cost-deko',
    storageBucket: 'cost-deko.appspot.com',
    iosClientId: '910592114279-clj7uv8o47dgfspnaajusvi9e6t25v8r.apps.googleusercontent.com',
    iosBundleId: 'com.justforlocks.costdeko.costdeko',
  );
}
